import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { writeWav, accentPatternTrack, chordProgressionTrack } from '../tests/helpers/synth-audio.js';

/**
 * Generates the original "WebMCP Demo Song" — an original instrumental in
 * Ab major (Ab · Fm · Db · Eb) at 63 BPM in 6/8, with intro / verse / chorus /
 * bridge / outro sections rendered as texture changes. This audio is
 * generated by this repo, not sampled from any recording.
 *
 * Layers are kept separate so previews can mix compiled guitar arrangements
 * against the identical backing:
 *   - backing.wav       percussion/pulse layer (non-harmonic)
 *   - original-guitar.wav  harmonic pad layer (the demo song's accompaniment)
 *   - original-full.wav    the two mixed
 *
 * Re-ingest after changing the texture: the graph must be re-analyzed.
 */

export const BPM = 63;
export const BEATS_PER_BAR = 6; // 6/8
export const SECONDS_PER_BAR = (BEATS_PER_BAR * 60) / BPM;
export const SAMPLE_RATE = 44_100;

export interface DemoChord {
  root: string;
  minor: boolean;
}

export const MAIN: DemoChord[] = [
  { root: 'Ab', minor: false },
  { root: 'Fm', minor: true },
  { root: 'Db', minor: false },
  { root: 'Eb', minor: false },
];

export const BRIDGE: DemoChord[] = [
  { root: 'Fm', minor: true },
  { root: 'Db', minor: false },
  { root: 'Ab', minor: false },
  { root: 'Eb', minor: false },
];

export type Texture = 'pad' | 'verse' | 'chorus';

export interface DemoSection {
  name: string;
  bars: number;
  texture: Texture;
  chords: DemoChord[];
}

/** Compositional plan — the same ground truth scripts/apply-demo-sections.ts stamps into the graph. */
export const SECTION_PLAN: DemoSection[] = [
  { name: 'INTRO', bars: 4, texture: 'pad', chords: MAIN },
  { name: 'VERSE', bars: 8, texture: 'verse', chords: MAIN },
  { name: 'CHORUS', bars: 8, texture: 'chorus', chords: MAIN },
  { name: 'BRIDGE', bars: 8, texture: 'verse', chords: BRIDGE },
  { name: 'CHORUS', bars: 8, texture: 'chorus', chords: MAIN },
  { name: 'OUTRO', bars: 4, texture: 'pad', chords: MAIN },
];

function concat(parts: Float32Array[]): Float32Array {
  const total = parts.reduce((n, p) => n + p.length, 0);
  const out = new Float32Array(total);
  let offset = 0;
  for (const p of parts) {
    out.set(p, offset);
    offset += p.length;
  }
  return out;
}

/** Percussion/pulse layer — the non-guitar backing. tempoFactor < 1 slows it. */
export function buildBacking(tempoFactor = 1, sampleRate = SAMPLE_RATE): Float32Array {
  const secondsPerBar = SECONDS_PER_BAR / tempoFactor;
  return concat(
    SECTION_PLAN.map((section) => {
      if (section.texture === 'pad') return new Float32Array(Math.round(section.bars * secondsPerBar * sampleRate));
      return accentPatternTrack([1, 0.25, 0.25, 0.6, 0.25, 0.25], section.bars, secondsPerBar, sampleRate);
    }),
  );
}

/** Harmonic pad layer (the demo song's own accompaniment). */
export function buildGuitarPads(tempoFactor = 1, sampleRate = SAMPLE_RATE): Float32Array {
  const secondsPerBar = SECONDS_PER_BAR / tempoFactor;
  return concat(
    SECTION_PLAN.map((section) => {
      const barsOfChords: DemoChord[] = [];
      for (let bar = 0; bar < section.bars; bar++) barsOfChords.push(section.chords[bar % section.chords.length]!);
      const pads = chordProgressionTrack(barsOfChords, secondsPerBar, sampleRate);
      if (section.texture !== 'chorus') return pads;
      const bright = chordProgressionTrack(barsOfChords, secondsPerBar, sampleRate);
      for (let i = 0; i < pads.length; i++) pads[i]! += bright[i]! * 0.45;
      return pads;
    }),
  );
}

function mix(a: Float32Array, b: Float32Array): Float32Array {
  const out = new Float32Array(Math.max(a.length, b.length));
  for (let i = 0; i < out.length; i++) out[i]! = (a[i] ?? 0) + (b[i] ?? 0);
  return out;
}

// --- CLI: write the stems (skipped when imported as a library) ---
const isMain = process.argv[1] !== undefined && import.meta.url.endsWith(path.basename(process.argv[1]));
if (isMain) {
  const OUT_DIR = process.argv[2] ?? path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'demo', 'audio');
  await mkdir(OUT_DIR, { recursive: true });
  const backing = buildBacking();
  const pads = buildGuitarPads();
  const full = mix(backing, pads);
  await writeWav(path.join(OUT_DIR, 'backing.wav'), backing, SAMPLE_RATE);
  await writeWav(path.join(OUT_DIR, 'original-guitar.wav'), pads, SAMPLE_RATE);
  await writeWav(path.join(OUT_DIR, 'original-full.wav'), full, SAMPLE_RATE);
  console.log(
    `WebMCP Demo Song: ${(full.length / SAMPLE_RATE).toFixed(1)}s (${SECTION_PLAN.reduce((n, s) => n + s.bars, 0)} bars) → ${OUT_DIR}/backing.wav, original-guitar.wav, original-full.wav`,
  );
}
